### PR TITLE
Fix issue Print pattern X with stars in c language #4

### PR DESCRIPTION
**Pull request by shahnanigans**
This should fix issue #4 

Thanks @rahulparshi !

### CODE REVIEW

**Review by rahulparshi — CHANGES_REQUESTED** [review]
Thank you @s37syed  for raising a PR.

Could you please make below changes
- Remove comments like //1 , //2
- Remove **printf("Enter size : ")** as mostly we will use online compilers like hacker rank.

If possible, Please add a switch case in Main.c for printing X pattern.

**Comment by shahnanigans** [comment]
> Thank you @s37syed for raising a PR.
> 
> Could you please make below changes
> 
>     * Remove comments like //1 , //2
> 
>     * Remove **printf("Enter size : ")** as mostly we will use online compilers like hacker rank.
> 
> 
> If possible, Please add a switch case in Main.c for printing X pattern.

I've made an update to my PR with these changes. 

Thanks for the review @rahulparshi ,

Shah

**Review by rahulparshi — CHANGES_REQUESTED** [review]
X.c file is looking good. 

For Main.c file
Please take the latest update from master branch and
After adding your code to Main.c input and output should look like something as below.

```C
sample Input
7 2
EX

output

*******  *     *
*         *   *
*          * *
*******     *
*          * *
*         *   *
*******  *     *
```

**Comment by rahulparshi** [comment]
Let me know if you are struck at something will try to help you out.

**Comment by rahulparshi** [comment]
your output for Main.c file

```c
*******   *    *  
*          *  *   
*           **    
*******     **    
*          *  *   
*         *    *  
*******  *      * 
```

Expected output is
```c
*******  *     *
*         *   *
*          * *
*******     *
*          * *
*         *   *
*******  *     *
```

In Main.c start inner for loop from j=1 and try modifying the conditions. It might help you to fix this.

**Comment by rahulparshi** [comment]
@s37syed are you able to finish this pull request?.

**Pull request closed without merging**
