### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by nymika**
added the code to print 'Y'

### CODE REVIEW

**Review by rahulparshi — CHANGES_REQUESTED** [review]
Thank you @nymika for raising a PR.

Your code **Individual patterns/y.c** works as expected only one minor change is required as mentioned in the below list.

Could you please make below changes
- Don't commit **Individual patterns/E** it is a BIN file.
- Use file name as Y.c(capital letter) in **Individual patterns/y.c**.
- In Main.c file Please refer patterns of other letters as copying the exact code from individual patterns directory will not work.
- Please include stdlib.h in the Main.c to use malloc function that is my mistake.

After adding your code in Main.c file your input and output should look as below.
```C
sample Input
7 2
EY

output

*******  *     *  
*         *   *  
*          * * 
*******     *
*           *
*           *
*******     *
```

**Comment by rahulparshi** [comment]
Hi @nymika, Is it possible for you to complete this by today EOD.

If you are struck at something let me know will try to help you.

**Comment by nymika** [comment]
I'm stuck at Main.c

**Comment by rahulparshi** [comment]
Please take the latest update from Master branch and add the below case statement to Main.c file. I had used your code from individual patterns :):)

```C
 case 'Y':
                for (int j = 1; j <= n; j++)
                {
                    if (i <= mid)
                    {
                        if (j == i || j == n + 1 - i)
                            printf("%c", character);
                        else
                            printf(" ");
                    }
                    else
                    {
                        if (j == mid)
                            printf("%c", character);
                        else
                            printf(" ");
                    }
                }
                break;
```

**Comment by nymika** [comment]
thankyou ! :)

**Comment by rahulparshi** [comment]
@all-contributors please add @nymika  for code

**Pull request merged**
